"""empty message

Revision ID: 987a761c2844
Revises: ac607024b6b8
Create Date: 2025-12-17 16:08:19.900374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987a761c2844'
down_revision = 'ac607024b6b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
